<?php

  module_load_include('inc', 'dls_components', '/includes/components/form/dls_components.form');
  module_load_include('inc', 'dls_components', '/includes/components/form/dls_components.label');
  module_load_include('inc', 'dls_components', '/includes/components/form/dls_components.textfield');
  module_load_include('inc', 'dls_components', '/includes/components/form/dls_components.textarea');
  module_load_include('inc', 'dls_components', '/includes/components/form/dls_components.checkbox');
  module_load_include('inc', 'dls_components', '/includes/components/form/dls_components.datefield');
  module_load_include('inc', 'dls_components', '/includes/components/form/dls_components.select');
  module_load_include('inc', 'dls_components', '/includes/components/form/dls_components.select_multiple');
  module_load_include('inc', 'dls_components', '/includes/components/form/dls_components.submit');