<?php

  module_load_include('inc', 'dls_components', '/includes/components/list/dls_components.linkListItem');
  module_load_include('inc', 'dls_components', '/includes/components/list/dls_components.linkListOfObjects');
  module_load_include('inc', 'dls_components', '/includes/components/list/dls_components.listItem');
  module_load_include('inc', 'dls_components', '/includes/components/list/dls_components.listOfObjects');
  module_load_include('inc', 'dls_components', '/includes/components/list/dls_components.unorderedList');
  module_load_include('inc', 'dls_components', '/includes/components/list/dls_components.listView');
  module_load_include('inc', 'dls_components', '/includes/components/list/dls_components.listAdapter');